services:
  frontend:
    build: ./frontend
    ports:
      - "$FRONTEND_PORT:3000"

  backend:
    build: ./backend
    ports:
      - "$BACKEND_PORT:5000"
    profiles:
      - backend

  "documents":
    build: ./docs
    ports:
      - "$DOCUMENTS_PORT:4001"
    profiles:
      - documents